/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package glory;

import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author I S Arandara
 */
public class GamePlay extends javax.swing.JFrame {

    /**
     * Creates new form GamePlay
     */
    public GamePlay() {
        initComponents();
    }

    /*public void fetchTableData()
    {
        DefaultTableModel model = (DefaultTableModel) Availableplayeres.playersTable.getModel();
        Availableplayeres.playersTable.getS
    }*/
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        player1 = new javax.swing.JLabel();
        player2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        player3 = new javax.swing.JLabel();
        JLabe = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        player4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        auto = new javax.swing.JButton();
        ok = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pause = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tilemiddle.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 100, 140));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tilemiddle.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 100, 140));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tilemiddle.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 100, 140));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tilemiddle.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 100, 140));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tilemiddle.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, 100, 140));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tilemiddle.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 420, 100, 140));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tilemiddle.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 420, 100, 140));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tilemiddle.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 420, 100, 140));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gamePlaygreen.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 110, 150));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gamePlaypurpal.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 110, 150));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gamePlayblue.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 110, 150));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/round.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, 50));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/otherplayers.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 120, 220, 50));

        player1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gamePlayblueOtherPly.png"))); // NOI18N
        jPanel1.add(player1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 190, 40, 50));

        player2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gamePlaygreenOtherPly.png"))); // NOI18N
        jPanel1.add(player2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 190, 40, 50));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gamePlaygreenOtherPly.png"))); // NOI18N
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 250, -1, 50));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gamePlayblueOtherPly.png"))); // NOI18N
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 310, -1, 50));

        player3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gamePlayblueOtherPly.png"))); // NOI18N
        jPanel1.add(player3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 250, 40, 50));

        JLabe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gamePlaypurpalOtherPly.png"))); // NOI18N
        jPanel1.add(JLabe, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 190, 40, 50));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gamePlaygreenOtherPly.png"))); // NOI18N
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 310, 40, 50));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gamePlaypurpalOtherPly.png"))); // NOI18N
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 310, -1, 50));

        jLabel23.setText("jLabel23");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 200, 120, 40));

        jLabel24.setText("jLabel24");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 260, 120, 40));

        jLabel25.setText("jLabel25");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 330, 120, 30));

        player4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gamePlaypurpalOtherPly.png"))); // NOI18N
        jPanel1.add(player4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 249, 40, 50));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/smallbox.png"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, 560, 280));

        auto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/auto1.png"))); // NOI18N
        auto.setContentAreaFilled(false);
        auto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                autoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                autoMouseReleased(evt);
            }
        });
        jPanel1.add(auto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 570, 170, 70));

        ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ok1.png"))); // NOI18N
        ok.setContentAreaFilled(false);
        ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                okMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                okMouseReleased(evt);
            }
        });
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        jPanel1.add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 570, 170, 70));

        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 600, 660, 30));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/textfield.png"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 580, 730, 70));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clock.png"))); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 100, 100));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/subbackground.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 1280, 590));

        pause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pause1.png"))); // NOI18N
        pause.setContentAreaFilled(false);
        pause.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pauseMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pauseMouseReleased(evt);
            }
        });
        pause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseActionPerformed(evt);
            }
        });
        jPanel1.add(pause, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wallpaperwood.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 770));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 770));

        setSize(new java.awt.Dimension(1396, 809));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_okActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void okMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okMousePressed
       ImageIcon IC = new ImageIcon(getClass().getResource("/images/ok2.png"));
       ok.setIcon(IC);
    }//GEN-LAST:event_okMousePressed

    private void okMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okMouseReleased
        ImageIcon IC = new ImageIcon(getClass().getResource("/images/ok1.png"));
       ok.setIcon(IC);
    }//GEN-LAST:event_okMouseReleased

    private void autoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_autoMousePressed
       ImageIcon IC = new ImageIcon(getClass().getResource("/images/auto2.png"));
       auto.setIcon(IC);
    }//GEN-LAST:event_autoMousePressed

    private void autoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_autoMouseReleased
        ImageIcon IC = new ImageIcon(getClass().getResource("/images/auto1.png"));
       auto.setIcon(IC);
    }//GEN-LAST:event_autoMouseReleased

    private void pauseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pauseMousePressed
        ImageIcon IC = new ImageIcon(getClass().getResource("/images/pause2.png"));
       pause.setIcon(IC);
    }//GEN-LAST:event_pauseMousePressed

    private void pauseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pauseMouseReleased
        ImageIcon IC = new ImageIcon(getClass().getResource("/images/pause1.png"));
       pause.setIcon(IC);
    }//GEN-LAST:event_pauseMouseReleased

    private void pauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseActionPerformed
        new PauseMenu ().setVisible(true);
    }//GEN-LAST:event_pauseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GamePlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GamePlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GamePlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GamePlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GamePlay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabe;
    private javax.swing.JButton auto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton ok;
    private javax.swing.JButton pause;
    private javax.swing.JLabel player1;
    private javax.swing.JLabel player2;
    private javax.swing.JLabel player3;
    private javax.swing.JLabel player4;
    // End of variables declaration//GEN-END:variables
}
