
package glory;

import javax.swing.ImageIcon;

/**
 *
 * @author I S Arandara
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        
      
        initComponents();
      
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        play = new javax.swing.JButton();
        highscore = new javax.swing.JButton();
        howtoplay = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        profile = new javax.swing.JButton();
        close = new javax.swing.JButton();
        gear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/play1.png"))); // NOI18N
        play.setContentAreaFilled(false);
        play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                playMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                playMouseReleased(evt);
            }
        });
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });
        jPanel1.add(play, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 600, 120));

        highscore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/high1.png"))); // NOI18N
        highscore.setContentAreaFilled(false);
        highscore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                highscoreMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                highscoreMouseReleased(evt);
            }
        });
        highscore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highscoreActionPerformed(evt);
            }
        });
        jPanel1.add(highscore, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 600, 120));

        howtoplay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/how1.png"))); // NOI18N
        howtoplay.setContentAreaFilled(false);
        howtoplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                howtoplayMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                howtoplayMouseReleased(evt);
            }
        });
        howtoplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                howtoplayActionPerformed(evt);
            }
        });
        jPanel1.add(howtoplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 500, 600, 130));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/coins.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 350, 80));

        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/profile1.png"))); // NOI18N
        profile.setContentAreaFilled(false);
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                profileMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                profileMouseReleased(evt);
            }
        });
        jPanel1.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 20, 80, 100));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close1.png"))); // NOI18N
        close.setContentAreaFilled(false);
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                closeMouseReleased(evt);
            }
        });
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 80, 100));

        gear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gear1.png"))); // NOI18N
        gear.setContentAreaFilled(false);
        gear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                gearMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                gearMouseReleased(evt);
            }
        });
        gear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gearActionPerformed(evt);
            }
        });
        jPanel1.add(gear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 20, 80, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wallpaperwood.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 770));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 770));

        setSize(new java.awt.Dimension(1396, 809));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
       
        new SelectServer ().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_playActionPerformed

    private void gearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gearActionPerformed

    private void closeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMousePressed
        ImageIcon IC = new ImageIcon(getClass().getResource("/images/close2.png"));
        close.setIcon(IC);
    }//GEN-LAST:event_closeMousePressed

    private void closeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseReleased
        ImageIcon IC = new ImageIcon(getClass().getResource("/images/close1.png"));
        close.setIcon(IC);

    }//GEN-LAST:event_closeMouseReleased

    private void profileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMousePressed
        ImageIcon IC = new ImageIcon(getClass().getResource("/images/profile2.png"));
        profile.setIcon(IC);
    }//GEN-LAST:event_profileMousePressed

    private void profileMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseReleased
        ImageIcon IC = new ImageIcon(getClass().getResource("/images/profile1.png"));
        profile.setIcon(IC);
    }//GEN-LAST:event_profileMouseReleased

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeActionPerformed

    private void howtoplayMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_howtoplayMousePressed
        ImageIcon IC = new ImageIcon(getClass().getResource("/images/how2.png"));
        howtoplay.setIcon(IC);
    }//GEN-LAST:event_howtoplayMousePressed

    private void howtoplayMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_howtoplayMouseReleased
        ImageIcon IC = new ImageIcon(getClass().getResource("/images/how1.png"));
        howtoplay.setIcon(IC);
    }//GEN-LAST:event_howtoplayMouseReleased

    private void howtoplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_howtoplayActionPerformed
        
        new HowtoPlay ().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_howtoplayActionPerformed

    private void highscoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highscoreActionPerformed
        
        new HighScore ().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_highscoreActionPerformed

    private void highscoreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_highscoreMousePressed
       ImageIcon IC = new ImageIcon(getClass().getResource("/images/high2.png"));
        highscore.setIcon(IC);
    }//GEN-LAST:event_highscoreMousePressed

    private void highscoreMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_highscoreMouseReleased
        ImageIcon IC = new ImageIcon(getClass().getResource("/images/high1.png"));
        highscore.setIcon(IC);
    }//GEN-LAST:event_highscoreMouseReleased

    private void playMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playMousePressed
        ImageIcon IC = new ImageIcon(getClass().getResource("/images/play2.png"));
        play.setIcon(IC);
    }//GEN-LAST:event_playMousePressed

    private void playMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playMouseReleased
        ImageIcon IC = new ImageIcon(getClass().getResource("/images/play1.png"));
        play.setIcon(IC);
    }//GEN-LAST:event_playMouseReleased

    private void gearMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gearMousePressed
        ImageIcon IC = new ImageIcon(getClass().getResource("/images/gear2.png"));
        gear.setIcon(IC);
    }//GEN-LAST:event_gearMousePressed

    private void gearMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gearMouseReleased
        ImageIcon IC = new ImageIcon(getClass().getResource("/images/gear1.png"));
        gear.setIcon(IC);
    }//GEN-LAST:event_gearMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    private javax.swing.JButton gear;
    private javax.swing.JButton highscore;
    private javax.swing.JButton howtoplay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton play;
    private javax.swing.JButton profile;
    // End of variables declaration//GEN-END:variables
}
