/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package glory;

import Model.Servers;
import static glory.Availableplayers.playersTable;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author I S Arandara
 */
public class SelectServer extends javax.swing.JFrame {

    /**
     * Creates new form SelectServer
     */
    public SelectServer() {
        initComponents();
        addServersToTable();
       
    }
    
    public ArrayList Servers()
    {
        ArrayList<Servers> servers = new ArrayList<Servers>();
        Servers server1 = new Servers("Server 1", 4);
        Servers server2 = new Servers("Server 2", 3);
        Servers server3 = new Servers("Server 3", 2);
        Servers server4 = new Servers("Server 4", 1);
        servers.add(server1);
        servers.add(server2);
        servers.add(server3);
        servers.add(server4);
        return servers;
    }
    
    public  void addServersToTable()
    {
        DefaultTableModel model = (DefaultTableModel) serverTable.getModel();
        ArrayList<Servers> servers = Servers();
        Object rowData[] = new Object[2];
        model.setRowCount(0);
        for(int i = 0; i < servers.size(); i++)
        {
            rowData[0] = servers.get(i).serverName;
            rowData[1] = servers.get(i).numofPlayers;
            model.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        join = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        createnewserver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        serverTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back1.png"))); // NOI18N
        back.setContentAreaFilled(false);
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                backMouseReleased(evt);
            }
        });
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 160, 70));

        join.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/join1.png"))); // NOI18N
        join.setContentAreaFilled(false);
        join.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                joinMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                joinMouseReleased(evt);
            }
        });
        join.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinActionPerformed(evt);
            }
        });
        jPanel1.add(join, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 50, 160, 70));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/textSelectServer.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 250, 50));

        createnewserver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/createnewserver1.png"))); // NOI18N
        createnewserver.setContentAreaFilled(false);
        createnewserver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                createnewserverMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                createnewserverMouseReleased(evt);
            }
        });
        createnewserver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createnewserverActionPerformed(evt);
            }
        });
        jPanel1.add(createnewserver, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 670, 370, 70));

        serverTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        serverTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Server Name", "Number of Players", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        serverTable.setRowHeight(20);
        jScrollPane1.setViewportView(serverTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 1120, 110));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/serverBackground1.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 1290, 510));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wallpaperwood.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 770));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 770));

        setSize(new java.awt.Dimension(1396, 809));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMousePressed
       ImageIcon IC = new ImageIcon(getClass().getResource("/images/back2.png"));
        back.setIcon(IC);
    }//GEN-LAST:event_backMousePressed

    private void backMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseReleased
        ImageIcon IC = new ImageIcon(getClass().getResource("/images/back1.png"));
        back.setIcon(IC);
    }//GEN-LAST:event_backMouseReleased

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        new Menu().setVisible(true);
        this.dispose();
        System.gc();
    }//GEN-LAST:event_backActionPerformed

    private void joinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinActionPerformed
        new Availableplayers ().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_joinActionPerformed

    private void joinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_joinMousePressed
        ImageIcon IC = new ImageIcon(getClass().getResource("/images/join2.png"));
        join.setIcon(IC);
    }//GEN-LAST:event_joinMousePressed

    private void joinMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_joinMouseReleased
        ImageIcon IC = new ImageIcon(getClass().getResource("/images/join1.png"));
        join.setIcon(IC);
    }//GEN-LAST:event_joinMouseReleased

    private void createnewserverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createnewserverMousePressed
        ImageIcon IC = new ImageIcon(getClass().getResource("/images/createnewserver2.png"));
        createnewserver.setIcon(IC);
                        
    }//GEN-LAST:event_createnewserverMousePressed

    private void createnewserverMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createnewserverMouseReleased
        ImageIcon IC = new ImageIcon(getClass().getResource("/images/createnewserver1.png"));
        createnewserver.setIcon(IC);                   
    }//GEN-LAST:event_createnewserverMouseReleased

    private void createnewserverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createnewserverActionPerformed
        new CreateServer ().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_createnewserverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectServer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton createnewserver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton join;
    private javax.swing.JTable serverTable;
    // End of variables declaration//GEN-END:variables
}
