/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package glory;

import javax.swing.ImageIcon;

/**
 *
 * @author I S Arandara
 */
public class TileSelect extends javax.swing.JFrame {

    /**
     * Creates new form TileSelect
     */
    public TileSelect() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        cancel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        select = new javax.swing.JButton();
        skip = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        vowels = new javax.swing.JRadioButton();
        consonants = new javax.swing.JRadioButton();
        next = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancelA.png"))); // NOI18N
        cancel.setContentAreaFilled(false);
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cancelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cancelMouseReleased(evt);
            }
        });
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel1.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 160, 80));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/green.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 140, 200));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/purple.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 140, 200));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blue.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 170, 150, 200));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tilemiddle.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 100, 130));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tilemiddle.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, -1, 130));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tilemiddle.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, -1, 130));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tilemiddle.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, -1, 130));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tilemiddle.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 400, -1, 130));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tilemiddle.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 400, -1, 130));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tilemiddle.png"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 400, -1, 130));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tilemiddle.png"))); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 400, -1, 130));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tilebackground.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 1280, 450));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clock.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 100, 110));

        select.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/select1.png"))); // NOI18N
        select.setContentAreaFilled(false);
        select.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                selectMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                selectMouseReleased(evt);
            }
        });
        jPanel1.add(select, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 630, 160, 80));

        skip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/skip1.png"))); // NOI18N
        skip.setContentAreaFilled(false);
        skip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                skipMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                skipMouseReleased(evt);
            }
        });
        skip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skipActionPerformed(evt);
            }
        });
        jPanel1.add(skip, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 630, 170, 80));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tilebottom.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 590, 120, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/consonants.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 690, 220, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/vowels.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 640, 130, 40));

        buttonGroup1.add(vowels);
        vowels.setContentAreaFilled(false);
        jPanel1.add(vowels, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 650, -1, -1));

        buttonGroup1.add(consonants);
        consonants.setContentAreaFilled(false);
        jPanel1.add(consonants, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 700, -1, -1));

        next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/next1.png"))); // NOI18N
        next.setContentAreaFilled(false);
        next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nextMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                nextMouseReleased(evt);
            }
        });
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel1.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 40, 160, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wallpaperwood.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 770));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 770));

        setSize(new java.awt.Dimension(1393, 810));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMousePressed
        ImageIcon IC = new ImageIcon(getClass().getResource("/images/cancelB.png"));
        cancel.setIcon(IC);
    }//GEN-LAST:event_cancelMousePressed

    private void cancelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseReleased
        ImageIcon IC = new ImageIcon(getClass().getResource("/images/cancelA.png"));
        cancel.setIcon(IC);
    }//GEN-LAST:event_cancelMouseReleased

    private void selectMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectMousePressed
         ImageIcon IC = new ImageIcon(getClass().getResource("/images/select2.png"));
        select.setIcon(IC);
    }//GEN-LAST:event_selectMousePressed

    private void selectMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectMouseReleased
          ImageIcon IC = new ImageIcon(getClass().getResource("/images/select1.png"));
        select.setIcon(IC);
    }//GEN-LAST:event_selectMouseReleased

    private void skipMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_skipMousePressed
        ImageIcon IC = new ImageIcon(getClass().getResource("/images/skip2.png"));
        skip.setIcon(IC);
    }//GEN-LAST:event_skipMousePressed

    private void skipMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_skipMouseReleased
        ImageIcon IC = new ImageIcon(getClass().getResource("/images/skip1.png"));
        skip.setIcon(IC);
    }//GEN-LAST:event_skipMouseReleased

    private void skipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_skipActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
       new SelectServer().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        new GamePlay().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nextActionPerformed

    private void nextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMousePressed
        ImageIcon IC = new ImageIcon(getClass().getResource("/images/next2.png"));
        next.setIcon(IC);
    }//GEN-LAST:event_nextMousePressed

    private void nextMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMouseReleased
        ImageIcon IC = new ImageIcon(getClass().getResource("/images/next1.png"));
        next.setIcon(IC);
    }//GEN-LAST:event_nextMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TileSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TileSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TileSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TileSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TileSelect().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancel;
    private javax.swing.JRadioButton consonants;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton next;
    private javax.swing.JButton select;
    private javax.swing.JButton skip;
    private javax.swing.JRadioButton vowels;
    // End of variables declaration//GEN-END:variables
}
