/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package glory;

import javax.swing.ImageIcon;

/**
 *
 * @author I S Arandara
 */
public class Win extends javax.swing.JFrame {

    /**
     * Creates new form Win
     */
    public Win() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainmenu = new javax.swing.JButton();
        playagain = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mainMenuA.png"))); // NOI18N
        mainmenu.setContentAreaFilled(false);
        mainmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mainmenuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mainmenuMouseReleased(evt);
            }
        });
        mainmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainmenuActionPerformed(evt);
            }
        });
        jPanel1.add(mainmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 650, 210, 70));

        playagain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/playAgain1.png"))); // NOI18N
        playagain.setContentAreaFilled(false);
        playagain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                playagainMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                playagainMouseReleased(evt);
            }
        });
        playagain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playagainActionPerformed(evt);
            }
        });
        jPanel1.add(playagain, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 650, 210, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Textwin.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 390, 110));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/textname.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 160, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/textscore.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, 120, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/textrewards.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 500, 240, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wallpaperwood.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 770));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 770));

        setSize(new java.awt.Dimension(1397, 810));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mainmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainmenuActionPerformed
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mainmenuActionPerformed

    private void playagainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playagainActionPerformed
        new Availableplayers ().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_playagainActionPerformed

    private void playagainMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playagainMousePressed
        ImageIcon IC = new ImageIcon(getClass().getResource("/images/playAgain2.png"));
        playagain.setIcon(IC);
    }//GEN-LAST:event_playagainMousePressed

    private void playagainMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playagainMouseReleased
       ImageIcon IC = new ImageIcon(getClass().getResource("/images/playAgain1.png"));
       playagain.setIcon(IC);
    }//GEN-LAST:event_playagainMouseReleased

    private void mainmenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainmenuMousePressed
        ImageIcon IC = new ImageIcon(getClass().getResource("/images/mainMenuB.png"));
        mainmenu.setIcon(IC);
    }//GEN-LAST:event_mainmenuMousePressed

    private void mainmenuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainmenuMouseReleased
        ImageIcon IC = new ImageIcon(getClass().getResource("/images/mainMenuA.png"));
        mainmenu.setIcon(IC);
    }//GEN-LAST:event_mainmenuMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Win.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Win.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Win.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Win.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Win().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mainmenu;
    private javax.swing.JButton playagain;
    // End of variables declaration//GEN-END:variables
}
